### ISSUE TITLE
Buttons disappears after a few runs

### ISSUE THREAD

**Issue by Nilusink** [MOD0912/Blackjack#2]
After some random amount of runs (not consistent), the HIT, STAND and HIT&RUN buttons dissapear

**Comment by Nilusink** [comment]
I just ran across the error again, here is the traceback:

```bash
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/nilusink/MELVIN/Mod_Blackjack/venv/lib/python3.11/site-packages/customtkinter/windows/widgets/ctk_button.py", line 553, in _clicked
    self._command()
  File "/home/nilusink/MELVIN/Mod_Blackjack/Blackjack.py", line 304, in close
    self.delet()
  File "/home/nilusink/MELVIN/Mod_Blackjack/Blackjack.py", line 92, in delet
    self.create_widgets()
  File "/home/nilusink/MELVIN/Mod_Blackjack/Blackjack.py", line 122, in create_widgets
    self.create_cards("Player")
  File "/home/nilusink/MELVIN/Mod_Blackjack/Blackjack.py", line 227, in create_cards
    self.stand()
  File "/home/nilusink/MELVIN/Mod_Blackjack/Blackjack.py", line 238, in stand
    self.create_cards("Croupier")
  File "/home/nilusink/MELVIN/Mod_Blackjack/Blackjack.py", line 227, in create_cards
    self.stand()
  File "/home/nilusink/MELVIN/Mod_Blackjack/Blackjack.py", line 238, in stand
    self.create_cards("Croupier")
  File "/home/nilusink/MELVIN/Mod_Blackjack/Blackjack.py", line 224, in create_cards
    self.end("player")
  File "/home/nilusink/MELVIN/Mod_Blackjack/Blackjack.py", line 274, in end
    self.hit_btn.configure(command=None)
  File "/home/nilusink/MELVIN/Mod_Blackjack/venv/lib/python3.11/site-packages/customtkinter/windows/widgets/ctk_button.py", line 441, in configure
    super().configure(require_redraw=require_redraw, **kwargs)
  File "/home/nilusink/MELVIN/Mod_Blackjack/venv/lib/python3.11/site-packages/customtkinter/windows/widgets/core_widget_classes/ctk_base_class.py", line 130, in configure
    super().configure(**pop_from_dict_by_set(kwargs, self._valid_tk_frame_attributes))  # configure tkinter.Frame
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1702, in configure
    return self._configure('configure', cnf, kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1689, in _configure
    return self._getconfigure(_flatten((self._w, cmd)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1673, in _getconfigure
    for x in self.tk.splitlist(self.tk.call(*args)):
                               ^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: invalid command name ".!ctkcanvas27.!ctkbutton"
```
